apiVersion: v1
kind: Secret
metadata:
  name: hrflow-secrets
type: Opaque
stringData:
  POSTGRES_DB: hrflow_dev
  POSTGRES_USER: hrflow
  POSTGRES_PASSWORD: hrflow_dev_pass

  DATABASE_URL: postgresql://hrflow:hrflow_dev_pass@postgres:5432/hrflow_dev

  JWT_SECRET: dev_secret_local_only
  JWT_REFRESH_SECRET: dev_refresh_secret_local_only

  STRIPE_SECRET_KEY: sk_test_placeholder