name: HRFlow Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  packages: read
  actions: read

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      skip_tests: ${{ steps.set-output.outputs.skip_tests }}
      docker_changed: ${{ steps.docker-filter.outputs.any_changed }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Détection des changements pour les tests
      - name: Détecter les fichiers modifiés hors extensions ignorées
        id: filter
        uses: tj-actions/changed-files@v45
        with:
          files_ignore: |
            **/*.yml
            **/*.yaml
            **/*.md
            **/*.png

      - name: Déterminer si les tests doivent être skip
        id: set-output
        run: |
          if [ "${{ steps.filter.outputs.any_changed }}" = "false" ]; then
            echo "skip_tests=true" >> "$GITHUB_OUTPUT"
          else
            echo "skip_tests=false" >> "$GITHUB_OUTPUT"
          fi

      # Détection spécifique aux fichiers Docker
      - name: Détecter les modifications Docker
        id: docker-filter
        uses: tj-actions/changed-files@v45
        with:
          files: |
            .github/workflows/docker.yml
            **/Dockerfile
            **/Dockerfile.*

  codeql:
    needs: changes
    if: needs.changes.outputs.skip_tests != 'true'
    uses: ./.github/workflows/codeql.yml
    secrets: inherit

  security:
    needs: changes
    if: needs.changes.outputs.skip_tests != 'true'
    uses: ./.github/workflows/security.yml
    secrets: inherit

  build-tests:
    needs: [changes, codeql, security]
    if: needs.changes.outputs.skip_tests != 'true'
    uses: ./.github/workflows/build-tests.yml
    secrets: inherit

  docker:
    needs: [build-tests, changes]
    if: >
      ${{ !cancelled() &&
      !failure() &&
      needs.changes.outputs.docker_changed == 'true' }}
    uses: ./.github/workflows/docker.yml
    secrets: inherit

  deploy-staging:
    needs: docker
    if: >
      ${{ !cancelled() && !failure() &&
      (startsWith(github.ref, 'refs/heads/dev-') || github.ref == 'refs/heads/main') &&
      github.event_name == 'push' }}
    uses: ./.github/workflows/deploy.yml
    with:
      environment: staging
    secrets: inherit

  deploy-production:
    needs: deploy-staging
    if: >
      ${{ !cancelled() && !failure() &&
      github.ref == 'refs/heads/main' &&
      github.event_name == 'push' }}
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production
    secrets: inherit